version: '3'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5429:5432
  web:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
    command: bash docker-compose-up.sh
    ports:
      - 8000:8000
  celeryworker:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    command: watchmedo auto-restart --directory=./apps --pattern=*.py --recursive -- celery -A apps.core worker -l info
  rabbitmq:
    image: rabbitmq:3.8.5
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  pgdata: