# Generated by Django 3.0.7 on 2020-06-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20200619_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='sqs_queue_url',
        ),
    ]
