# Generated by Django 3.0.7 on 2020-06-16 23:40

import apps.user.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.TextField(verbose_name="First Name")),
                ("last_name", models.TextField(verbose_name="Last Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"abstract": False,},
            managers=[("objects", apps.user.models.UserManager()),],
        ),
    ]
