# Generated by Django 3.0.7 on 2020-06-26 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200619_1619'),
        ('user', '0003_auto_20200626_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(through='account.AccountMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(),
        ),
    ]
